#!/usr/bin/env python3

###
# Problem 2
# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
###
# Solution: O(n) time | O(1) space
###
import cProfile

def sum_of_even_Fibonnaci(max_value):
    n1, n2 = 1, 2
    r  = 0
    while n2 < max_value:
        if (n2 % 2 == 0):
            r += n2
        n1, n2 = n2, n2 + n1
    else:
        return r

cProfile.run('print(sum_of_even_Fibonnaci(4e6))')
